language: node_js
sudo: false
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g serverless
script:
  - npm t
  - sls deploy
branches:
  only:
    - master
